version: '3.4'

services:
  errormessagesapi:
    image: ${DOCKER_REGISTRY-}errormessagesapi
    container_name: error-messages-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MongoDB__Host: mongo
    depends_on:
      - mongo
    networks:
      - error-messgeapi-network
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
     #- ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - error-messgeapi-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - error-messgeapi-network
volumes:
  mongo-data:
    driver: local
networks:
  error-messgeapi-network:
    driver: bridge